#%RAML 1.0 DataType
type: object
properties:
  roomId:
    description: Unique Room ID to which user wants to enter
    type: number
    required: true
  userId:
    description: User ID of the user who wants to enter the above roomId
    type: number
    required: true
    